# Generated by Django 4.2 on 2023-12-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_communityworker_visit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olderadult',
            name='visit_id',
        ),
        migrations.AddField(
            model_name='visit',
            name='older_adults',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.olderadult'),
        ),
        migrations.AlterField(
            model_name='communityworker',
            name='visit_id',
            field=models.ManyToManyField(blank=True, related_name='visit_id', to='api.visit'),
        ),
    ]
