# Generated by Django 4.2 on 2023-12-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_olderadult_visit_id_visit_older_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='rudas_item16',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
